# Navigation Links
#   To link a page section, specify the URL as a hash `/#` followed by the `id` of the section.
#   The `weight` parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /#top
    weight: 10
  - name: The Program
    url: /#program
    weight: 20
  - name: Resources
    weight: 30
#    hasChildren: true
#  - parent: Resources
#    name: Program Materials
#    url: materials/
  - name: Donate
    url: /#donate
    weight: 40
