# Navigation Links
#   To link a page section, specify the URL as a hash `/#` followed by the `id` of the section.
#   The `weight` parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /#top
    weight: 10
  - name: About the Program
    url: /#program
    weight: 20
  - name: The NGU Team
    url: /people
    weight: 30
  - name: Testimonials
    url: /#testimonials
    weight: 40
  - name: Donate to the Program
    url: /#donate
    weight: 50
  - name: NGU in the News
    url: /#news
    weight: 60
  - name: Contact Us
    url: /#contact
    weight: 70
